// data.js - Sau khi sửa
export const hours = Array.from({ length: 10 }, (_, i) => i + 1);

export const classes = [
  {
    id: "cs1",
    name: "Chủ nghĩa xã hội khoa học",
    day: "Hai",
    startHour: 1,
    duration: 2,
    room: "K.C106",
    color: "#65b2d7",
  },
  {
    id: "it1",
    name: "Đảm bảo chất lượng và Kiểm thử phần mềm",
    day: "Ba",
    startHour: 1,
    duration: 2,
    room: "K.A105",
    color: "#8c7847",
  },
  {
    id: "it2",
    name: "Thiết kế UX/UI",
    day: "Năm",
    startHour: 1,
    duration: 1,
    room: "K.A201",
    color: "#478144",
  },
  {
    id: "it3",
    name: "Phát triển ứng dụng di động đa nền tảng",
    day: "Sáu",
    startHour: 1,
    duration: 1,
    room: "V.A401",
    color: "#8a4066",
  },
  {
    id: "it4",
    name: "Chuyên đề 3 (IT)",
    day: "Tư",
    startHour: 3,
    duration: 2,
    room: "K.A105",
    color: "#4b3c7b",
  },
  {
    id: "ko1",
    name: "Tiếng Hàn doanh nghiệp",
    day: "Hai",
    startHour: 6,
    duration: 4,
    room: "K.A105",
    color: "#6a0a09",
  },
  {
    id: "ko2",
    name: "Tiếng Hàn doanh nghiệp",
    day: "Tư",
    startHour: 6,
    duration: 4,
    room: "K.A105",
    color: "#4b3c7b",
  },
  {
    id: "it5",
    name: "Quản trị dự án phần mềm",
    day: "Năm",
    startHour: 6,
    duration: 2,
    room: "K.A207",
    color: "#478144",
  },
  {
    id: "it6",
    name: "Điện toán đám mây",
    day: "Sáu",
    startHour: 6,
    duration: 2,
    room: "K.A105",
    color: "#8c7847",
  },
];
