export const Accounts = [
  {
    id: 1,
    username: "iammaiami",
    pass: "1234",
    name: "Nguyen Mai",
    email: "duoinuicholantu6x9@gmail.com",
    role: "staff",
    code: "NV-HC-1",
  },

  {
    id: 2,
    username: "iemmeiemi",
    pass: "1234",
    name: "Mai Nguyen",
    email: "",
    role: "teacher",
    code: "GV-IT-2",
  },
  {
    id: 3,
    username: "maimaimai",
    pass: "1234",
    name: "Thuy Mai",
    email: "",
    role: "teacher",
    code: "GV-IT-3",
  },
  {
    id: 4,
    username: "thanhtran",
    pass: "1234",
    name: "Tran Thanh",
    email: "",
    role: "teacher",
    code: "GV-IT-4",
  },
  {
    id: 5,
    username: "nghianguyen",
    pass: "1234",
    name: "Nguyen Nghia",
    email: "",
    role: "teacher",
    code: "GV-IT-5",
  },
  {
    id: 6,
    username: "quocanh",
    pass: "1234",
    name: "Le Quoc Anh",
    email: "",
    role: "teacher",
    code: "GV-IT-6",
  },

  {
    id: 7,
    username: "sv01",
    pass: "1234",
    name: "Nguyen Van A",
    email: "",
    role: "student",
    code: "SV-IT-7",
  },
  {
    id: 8,
    username: "sv02",
    pass: "1234",
    name: "Tran Thi B",
    email: "",
    role: "student",
    code: "SV-IT-8",
  },
  {
    id: 9,
    username: "sv03",
    pass: "1234",
    name: "Le Van C",
    email: "",
    role: "student",
    code: "SV-IT-9",
  },
  {
    id: 10,
    username: "sv04",
    pass: "1234",
    name: "Pham Thi D",
    email: "",
    role: "student",
    code: "SV-IT-10",
  },
  {
    id: 11,
    username: "sv05",
    pass: "1234",
    name: "Hoang Van E",
    email: "",
    role: "student",
    code: "SV-IT-11",
  },
  {
    id: 12,
    username: "sv06",
    pass: "1234",
    name: "Nguyen Thi F",
    email: "",
    role: "student",
    code: "SV-IT-12",
  },
  {
    id: 13,
    username: "sv07",
    pass: "1234",
    name: "Tran Van G",
    email: "",
    role: "student",
    code: "SV-IT-13",
  },
  {
    id: 14,
    username: "sv08",
    pass: "1234",
    name: "Le Thi H",
    email: "",
    role: "student",
    code: "SV-IT-14",
  },
  {
    id: 15,
    username: "sv09",
    pass: "1234",
    name: "Pham Van I",
    email: "",
    role: "student",
    code: "SV-IT-15",
  },
  {
    id: 16,
    username: "sv10",
    pass: "1234",
    name: "Hoang Thi J",
    email: "",
    role: "student",
    code: "SV-IT-16",
  },
  {
    id: 17,
    username: "sv11",
    pass: "1234",
    name: "Nguyen Van K",
    email: "",
    role: "student",
    code: "SV-IT-17",
  },
  {
    id: 18,
    username: "sv12",
    pass: "1234",
    name: "Tran Thi L",
    email: "",
    role: "student",
    code: "SV-IT-18",
  },
  {
    id: 19,
    username: "sv13",
    pass: "1234",
    name: "Le Van M",
    email: "",
    role: "student",
    code: "SV-IT-19",
  },
  {
    id: 20,
    username: "sv14",
    pass: "1234",
    name: "Pham Thi N",
    email: "",
    role: "student",
    code: "SV-IT-20",
  },
  {
    id: 21,
    username: "sv15",
    pass: "1234",
    name: "Hoang Van O",
    email: "",
    role: "student",
    code: "SV-IT-21",
  },
  {
    id: 22,
    username: "sv16",
    pass: "1234",
    name: "Nguyen Thi P",
    email: "",
    role: "student",
    code: "SV-IT-22",
  },
  {
    id: 23,
    username: "sv17",
    pass: "1234",
    name: "Tran Van Q",
    email: "",
    role: "student",
    code: "SV-IT-23",
  },
  {
    id: 24,
    username: "sv18",
    pass: "1234",
    name: "Le Thi R",
    email: "",
    role: "student",
    code: "SV-IT-24",
  },
  {
    id: 25,
    username: "sv19",
    pass: "1234",
    name: "Pham Van S",
    email: "",
    role: "student",
    code: "SV-IT-25",
  },
  {
    id: 26,
    username: "sv20",
    pass: "1234",
    name: "Hoang Thi T",
    email: "",
    role: "student",
    code: "SV-IT-26",
  },
  {
    id: 27,
    username: "sv21",
    pass: "1234",
    name: "Nguyen Van U",
    email: "",
    role: "student",
    code: "SV-IT-27",
  },
  {
    id: 28,
    username: "sv22",
    pass: "1234",
    name: "Tran Thi V",
    email: "",
    role: "student",
    code: "SV-IT-28",
  },
  {
    id: 29,
    username: "sv23",
    pass: "1234",
    name: "Le Van W",
    email: "",
    role: "student",
    code: "SV-IT-29",
  },
  {
    id: 30,
    username: "sv24",
    pass: "1234",
    name: "Pham Thi X",
    email: "",
    role: "student",
    code: "SV-IT-30",
  },
  {
    id: 31,
    username: "sv25",
    pass: "1234",
    name: "Hoang Van Y",
    email: "",
    role: "student",
    code: "SV-IT-31",
  },
  {
    id: 32,
    username: "sv26",
    pass: "1234",
    name: "Nguyen Thi Z",
    email: "",
    role: "student",
    code: "SV-IT-32",
  },
  {
    id: 33,
    username: "sv27",
    pass: "1234",
    name: "Tran Van AA",
    email: "",
    role: "student",
    code: "SV-IT-33",
  },
  {
    id: 34,
    username: "sv28",
    pass: "1234",
    name: "Le Thi BB",
    email: "",
    role: "student",
    code: "SV-IT-34",
  },
  {
    id: 35,
    username: "sv29",
    pass: "1234",
    name: "Pham Van CC",
    email: "",
    role: "student",
    code: "SV-IT-35",
  },
  {
    id: 36,
    username: "sv30",
    pass: "1234",
    name: "Hoang Thi DD",
    email: "",
    role: "student",
    code: "SV-IT-36",
  },
];

export const getStudents = (page = 1, pageSize = 15) => {
    const students = Accounts.filter((account) => account.role === "student");
    const start = (page - 1) * pageSize;
    return students.slice(start, start + pageSize);
};

export const getTeachers = (page = 1, pageSize = 15) => {
    const teachers = Accounts.filter((account) => account.role === "teacher");
    const start = (page - 1) * pageSize;
    return teachers.slice(start, start + pageSize);
};

export const getAccountById = (id) => {
    return Accounts.find((account) => account.id === parseInt(id));
};