export const createNewLesson = (lesson) => {
  const newId = Lesson.length ? Lesson[Lesson.length - 1].id + 1 : 1;
  const newLesson = { id: newId, ...lesson };
  Lesson.push(newLesson);
  return newLesson;
}

export const getLessonsByCourseId = (courseId) => {
  return Lesson.filter((lesson) => lesson.course_ref === parseInt(courseId));
}

export const getLessonById = (id) => {
  return Lesson.find((l) => l.id === parseInt(id));
}

export var Lesson = [
  {
    id: 1,
    course_ref: 1,
    title: "Giới thiệu về lập trình web",
    content: "Các khái niệm cơ bản và cách hoạt động của web.",
    duration: "1",
    assets: [],
    order: 1,
  },
  {
    id: 2,
    course_ref: 1,
    title: "Cấu trúc HTML cơ bản",
    content: "Học cách tạo cấu trúc trang web bằng HTML.",
    duration: "1",
    assets: [],
    order: 2,
  },
  {
    id: 3,
    course_ref: 1,
    title: "Tạo kiểu với CSS",
    content: "Áp dụng CSS để thiết kế giao diện web.",
    duration: "1",
    assets: [],
    order: 3,
  },
  {
    id: 4,
    course_ref: 1,
    title: "CSS nâng cao",
    content: "Sử dụng Flexbox, Grid và pseudo-class trong CSS.",
    duration: "1",
    assets: [],
    order: 4,
  },
  {
    id: 5,
    course_ref: 1,
    title: "Giới thiệu JavaScript",
    content: "Làm quen với cú pháp và biến trong JavaScript.",
    duration: "1",
    assets: [],
    order: 5,
  },
  {
    id: 6,
    course_ref: 1,
    title: "DOM và sự kiện",
    content: "Cách thao tác DOM và xử lý sự kiện trong JS.",
    duration: "1",
    assets: [],
    order: 6,
  },
  {
    id: 7,
    course_ref: 1,
    title: "Thực hành mini project",
    content: "Tạo một trang web đơn giản tích hợp HTML/CSS/JS.",
    duration: "2",
    assets: [],
    order: 7,
  },

  {
    id: 8,
    course_ref: 2,
    title: "Giới thiệu cơ sở dữ liệu",
    content: "Khái niệm, vai trò và các loại CSDL.",
    duration: "1",
    assets: [],
    order: 1,
  },
  {
    id: 9,
    course_ref: 2,
    title: "Mô hình quan hệ",
    content: "Các bảng, khóa và quan hệ giữa các bảng.",
    duration: "1",
    assets: [],
    order: 2,
  },
  {
    id: 10,
    course_ref: 2,
    title: "Ngôn ngữ SQL cơ bản",
    content: "Học cú pháp SELECT, INSERT, UPDATE, DELETE.",
    duration: "1",
    assets: [],
    order: 3,
  },
  {
    id: 11,
    course_ref: 2,
    title: "SQL nâng cao",
    content: "JOIN, GROUP BY, HAVING và các hàm tổng hợp.",
    duration: "1",
    assets: [],
    order: 4,
  },
  {
    id: 12,
    course_ref: 2,
    title: "Thiết kế cơ sở dữ liệu",
    content: "Chuẩn hóa dữ liệu và lập mô hình ERD.",
    duration: "1",
    assets: [],
    order: 5,
  },
  {
    id: 13,
    course_ref: 2,
    title: "Thực hành với MySQL",
    content: "Tạo và truy vấn dữ liệu trên MySQL.",
    duration: "2",
    assets: [],
    order: 6,
  },

  {
    id: 14,
    course_ref: 3,
    title: "Giới thiệu Java và OOP",
    content: "Tổng quan Java và lập trình hướng đối tượng.",
    duration: "1",
    assets: [],
    order: 1,
  },
  {
    id: 15,
    course_ref: 3,
    title: "Lớp và đối tượng",
    content: "Tạo lớp, thuộc tính và phương thức trong Java.",
    duration: "1",
    assets: [],
    order: 2,
  },
  {
    id: 16,
    course_ref: 3,
    title: "Kế thừa",
    content: "Cách tái sử dụng mã bằng tính kế thừa.",
    duration: "1",
    assets: [],
    order: 3,
  },
  {
    id: 17,
    course_ref: 3,
    title: "Đa hình",
    content: "Hiểu cơ chế đa hình trong Java.",
    duration: "1",
    assets: [],
    order: 4,
  },
  {
    id: 18,
    course_ref: 3,
    title: "Đóng gói và truy cập",
    content: "Các mức độ truy cập và tính đóng gói.",
    duration: "1",
    assets: [],
    order: 5,
  },
  {
    id: 19,
    course_ref: 3,
    title: "Xử lý ngoại lệ",
    content: "Cách xử lý lỗi bằng try-catch-finally.",
    duration: "1",
    assets: [],
    order: 6,
  },
  {
    id: 20,
    course_ref: 3,
    title: "Mini project Java OOP",
    content: "Xây dựng ứng dụng quản lý sinh viên.",
    duration: "2",
    assets: [],
    order: 7,
  },

  {
    id: 21,
    course_ref: 4,
    title: "Giới thiệu phân tích hệ thống",
    content: "Vai trò của phân tích hệ thống trong phát triển phần mềm.",
    duration: "1",
    assets: [],
    order: 1,
  },
  {
    id: 22,
    course_ref: 4,
    title: "Thu thập yêu cầu",
    content: "Phương pháp phỏng vấn, khảo sát, quan sát.",
    duration: "1",
    assets: [],
    order: 2,
  },
  {
    id: 23,
    course_ref: 4,
    title: "Mô hình hóa yêu cầu",
    content: "Dùng biểu đồ use case và biểu đồ hoạt động.",
    duration: "1",
    assets: [],
    order: 3,
  },
  {
    id: 24,
    course_ref: 4,
    title: "Thiết kế kiến trúc hệ thống",
    content: "Xác định module, phân lớp và kiến trúc tổng thể.",
    duration: "1",
    assets: [],
    order: 4,
  },
  {
    id: 25,
    course_ref: 4,
    title: "Thiết kế cơ sở dữ liệu",
    content: "Kết nối giữa phân tích và thiết kế DB.",
    duration: "1",
    assets: [],
    order: 5,
  },
  {
    id: 26,
    course_ref: 4,
    title: "Lập tài liệu hệ thống",
    content: "Cách viết tài liệu đặc tả yêu cầu và thiết kế.",
    duration: "1",
    assets: [],
    order: 6,
  },

  {
    id: 27,
    course_ref: 5,
    title: "Tổng quan mạng máy tính",
    content: "Khái niệm, thành phần và mô hình mạng.",
    duration: "1",
    assets: [],
    order: 1,
  },
  {
    id: 28,
    course_ref: 5,
    title: "Tầng vật lý và liên kết dữ liệu",
    content: "Chức năng và giao thức cơ bản.",
    duration: "1",
    assets: [],
    order: 2,
  },
  {
    id: 29,
    course_ref: 5,
    title: "Tầng mạng",
    content: "Giao thức IP, định tuyến và địa chỉ IP.",
    duration: "1",
    assets: [],
    order: 3,
  },
  {
    id: 30,
    course_ref: 5,
    title: "Tầng vận chuyển",
    content: "TCP, UDP và kiểm soát luồng.",
    duration: "1",
    assets: [],
    order: 4,
  },
  {
    id: 31,
    course_ref: 5,
    title: "Tầng ứng dụng",
    content: "HTTP, DNS, SMTP và các dịch vụ phổ biến.",
    duration: "1",
    assets: [],
    order: 5,
  },
  {
    id: 32,
    course_ref: 5,
    title: "Bảo mật mạng",
    content: "Mã hóa, tường lửa, VPN và bảo mật thông tin.",
    duration: "1",
    assets: [],
    order: 6,
  },
  {
    id: 33,
    course_ref: 5,
    title: "Thực hành cấu hình mạng",
    content: "Thực hành mô phỏng mạng máy tính.",
    duration: "2",
    assets: [],
    order: 7,
  },
];
